### ISSUE TITLE
OperationalError: no such table: notes

### ISSUE THREAD

**Issue by HabeltWi** [eachiaradia/ExportGeopaparazzi#11]
When I attempt to run the plugin I get this exception after selecting the .gpap file. Any ideas what could be causing this?

```
OperationalError: no such table: notes 
Traceback (most recent call last):
  File "/home/wha/.qgis2/python/plugins/ExportGeopaparazzi/ExportGeopaparazzi.py", line 78, in openExportDatasetGUI
    ExportDataset(pathToDB, DBname,currentpath)
  File "/home/wha/.qgis2/python/plugins/ExportGeopaparazzi/tools/ExportDataset.py", line 114, in ExportDataset
    notes = cur.execute("SELECT * FROM notes")
OperationalError: no such table: notes
```

**Comment by eachiaradia** [comment]
It means that there is no table named "notes" in the gpap file. I need to know what version of Geopaparazzi you are using and if you recorded "notes" using Geopaparazzi. In the meantime, I will modify the code to manage such kind of errors.

**Comment by HabeltWi** [comment]
I am currently using Geopaparazzi version 5.1.2. I have recorded two notes using a custom form. The notes are displayed correctly in the Notes List.

**Comment by eachiaradia** [comment]
Unfortunately, I have no way to test the lastest release of geopaparazzi because compatibility issue with my android phone. Looking in the source code of Geopaparazzi, apparentely there is no reason why the exportGeopaparazzi plugin shouldn't work. Could you please upload a sample gpap file?

**Comment by HabeltWi** [comment]
[fountains.zip](https://github.com/eachiaradia/ExportGeopaparazzi/files/670533/fountains.zip)

**Comment by eachiaradia** [comment]
Thanks! Under windows 7, QGIS 2.14 and Exportgeopaparazzi 0.1.3 (the version currently published on the qgis repository) the plugin works correctly. Could you provide your O.S. (win or linux) and your Qgis version?

**Comment by HabeltWi** [comment]
I am currently using QGIS version 2.14.5 and Linux Ubuntu 16.04

**Comment by eachiaradia** [comment]
Ok after some time spent to setting up a virtual machine, I finally can reproduce the error. I hope to find the cause as soon as possible.

**Comment by eachiaradia** [comment]
Ok I found and fixed it. You can try a preview downloading the latest version from github. I'm planning also to update it on qgis repository.

**Comment by HabeltWi** [comment]
Great to see it working now! I hope you had a good start to 2017.
